# Generated by Django 4.2 on 2023-09-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='watchAgain',
        ),
    ]
